/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyingresos;

import proyingresos.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matgr
 */
public class aportaciones extends javax.swing.JFrame {

    /**
     * Creates new form aportaciones
     */
     DefaultTableModel modelo = new DefaultTableModel();
    public aportaciones() {
        initComponents();
         Date fa=new Date();
         String mesctual1 = null;
         String diaactual1="";
    int aniactual=fa.getYear()+1900;
    int mesctual=fa.getMonth()+1;
    int diaactual=fa.getDate();
        if (mesctual<10) {
           mesctual1="0"+mesctual;
        }else{
            mesctual1=""+mesctual;
        }
        if (diaactual<10) {
           diaactual1="0"+diaactual;
        }else{
            diaactual1=""+diaactual;
        }
    lblfecha.setText(aniactual+"-"+mesctual1+"-"+diaactual1);
               try {
            japortacion.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT cedula, nombre, telefono, fecha_pago FROM aportaciones";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Cedula");
            modelo.addColumn("Nombre");
            modelo.addColumn("Telefono");
            modelo.addColumn("Fecha Pago");

            int[] anchos = {50, 100, 50, 150};
            for (int i = 0; i < japortacion.getColumnCount(); i++) {
                japortacion.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        japortacion = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JLabel();
        txtnombre = new javax.swing.JLabel();
        txttelefono = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("  APORTACIONES MENSUALES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 13, 224, 53));

        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 73, -1, -1));

        lblfecha.setText("...");
        jPanel1.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 73, 86, -1));

        jLabel4.setText("Ingrese la cedula del usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, 175, 26));

        txtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 109, 200, -1));

        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 108, -1, -1));

        jLabel19.setText("Usuarios que han realizado su aporte mensual:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, 284, 26));

        japortacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        japortacion.setToolTipText("");
        japortacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                japortacionMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(japortacion);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 225, 395, 390));

        jLabel20.setText("Cedula:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 225, 65, 25));

        jLabel12.setText("Nombre:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 279, 56, 25));

        jLabel13.setText("Telefono:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 56, 25));

        txtcedula.setText("...");
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 225, 128, 25));

        txtnombre.setText("...");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 279, 258, 25));

        txttelefono.setText("...");
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 138, 25));

        btnGuardar1.setText("Registrar Aporte");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 397, -1, -1));

        jLabel3.setText("Datos usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed

        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        try{

            Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM registro WHERE cedula = ?");
            ps.setString(1, txtCampo.getText());

            rs = ps.executeQuery();

            if(rs.next()){
                txtcedula.setText(rs.getString("cedula"));
                txtnombre.setText(rs.getString("nombre"));

                txttelefono.setText(rs.getString("telefono"));

            } else {
                JOptionPane.showMessageDialog(null, "El usuario no se encuentra en el registro");
            }

        } catch(Exception e){
            System.err.println(e);
        }
txtCampo.setText("");
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void japortacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_japortacionMouseClicked

    }//GEN-LAST:event_japortacionMouseClicked

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
         PreparedStatement ps = null;
        if (("...".equals(txtcedula.getText()))||("".equals(txtcedula.getText()))) {
            JOptionPane.showMessageDialog(null, "Error no se encuentran llenos todos los campos");
        }else{
            
         try {
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();
            ps = conn.prepareStatement("INSERT INTO aportaciones (cedula, nombre, telefono, fecha_pago) VALUES (?,?,?,?)");
            ps.setString(1, txtcedula.getText());
            ps.setString(2, txtnombre.getText());
            ps.setString(3, txttelefono.getText());
            ps.setString(4, lblfecha.getText());

            ps.execute();

            JOptionPane.showMessageDialog(null, "Aportacion Registrada");
            Object[] fila = new Object[4];
            fila[0] = txtcedula.getText();
            fila[1] = txtnombre.getText();
            fila[2] = txttelefono.getText();
            fila[3] = lblfecha.getText();
            modelo.addRow(fila);

            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al registrar aportacion");
            System.out.println(ex);
        }
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed
 private void limpiar() {
        txtcedula.setText("");
        txtnombre.setText("");
        txttelefono.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aportaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aportaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable japortacion;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JTextField txtCampo;
    private javax.swing.JLabel txtcedula;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JLabel txttelefono;
    // End of variables declaration//GEN-END:variables
}
