/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyingresos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin
 */
public class PnlEgresos extends javax.swing.JPanel {

    /**
     * Creates new form PnlEgresos
     */
    public PnlEgresos() {
        initComponents();
        int n, m, r;
        Date fa = new Date();
        String mesctual1 = null;
        String diaactual1 = "";
        int aniactual = fa.getYear() + 1900;
        int mesctual = fa.getMonth() + 1;
        int diaactual = fa.getDate();
        if (mesctual < 10) {
            mesctual1 = "0" + mesctual;
        } else {
            mesctual1 = "" + mesctual;
        }
        if (diaactual < 10) {
            diaactual1 = "0" + diaactual;
        } else {
            diaactual1 = "" + diaactual;
        }
        lblfecha.setText(aniactual + "-" + mesctual1 + "-" + diaactual1);
        Random dado = new Random();
        n = dado.nextInt(9);
        m = dado.nextInt(9);
        r = dado.nextInt(9);
        txtcedula2.setText("0" + n + m + r);

        aut2();
        tabla();
        sumar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcuotas = new javax.swing.JTable();
        txtnombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        comunes = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtcedula2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(765, 900));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(765, 900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Egresos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 200, 53));

        jLabel2.setText("Egresos registrados:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 227, 26));

        jtcuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtcuotas.setToolTipText("");
        jtcuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcuotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtcuotas);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, 400, 440));

        txtnombre.setText("...");
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 225, 220, 25));

        jLabel5.setText("Valor gasto :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 263, 90, 25));

        jLabel6.setText("Autoriza:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 225, 60, 25));

        jLabel8.setText("Fecha:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 60, 25));

        lblfecha.setText("...");
        jPanel2.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, 25));

        jLabel11.setText("Motivo gasto:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 301, 110, 25));

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 140, 40));

        jLabel4.setText("Datos egreso:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 120, -1));
        jPanel2.add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 130, -1));

        comunes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Comida", "Cafe", "Licor", "Medicinas", "Emergencia", "Otros", " " }));
        jPanel2.add(comunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 240, -1));

        jLabel9.setText("Codigo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 187, 60, 25));

        txtcedula2.setText("...");
        jPanel2.add(txtcedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 187, 160, 25));

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtcuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcuotasMouseClicked

    }//GEN-LAST:event_jtcuotasMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        PreparedStatement ps = null;
        int n,m,r;
        try {
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();
            ps = conn.prepareStatement("INSERT INTO egresos (codigo,autoriza,valor_gasto,motivo_gasto,fecha_registro) VALUES (?,?,?,?,?)");
            ps.setString(1, txtcedula2.getText());
            ps.setString(2, txtnombre.getText());
            ps.setString(3, txtvalor.getText());
            ps.setString(4, comunes.getSelectedItem().toString());
            ps.setString(5, lblfecha.getText());
            ps.execute();

            JOptionPane.showMessageDialog(null, "Gasto registrado");
            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Registrar gasto");
            System.out.println(ex);
        }
        Random dado = new Random();
        n = dado.nextInt(9);
        m = dado.nextInt(9);
        r = dado.nextInt(9);
        txtcedula2.setText("0" + n + m + r);
        tabla();
        sumar();
    }//GEN-LAST:event_btnGuardarActionPerformed
    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            jtcuotas.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT codigo,autoriza,valor_gasto,motivo_gasto,fecha_registro  FROM egresos";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Codigo");
            modelo.addColumn("Autoriza");
            modelo.addColumn("Valor gasto");
            modelo.addColumn("Motivo gasto");
            modelo.addColumn("Fecha registro");

            int[] anchos = {40, 60, 50, 110, 60};
            for (int i = 0; i < jtcuotas.getColumnCount(); i++) {
                jtcuotas.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    public void sumar() {
        double fila = 0.0;
        double total = 0.0;
        PreparedStatement ps = null;
        for (int i = 0; i < jtcuotas.getRowCount(); i++) {
            fila = Double.parseDouble(jtcuotas.getValueAt(i, 2).toString());
            total += fila;
        }
        try {
            Conexion objCon = new Conexion();
            com.mysql.jdbc.Connection conn = objCon.getConexion();

            ps = conn.prepareStatement("UPDATE reporte SET totalegresos=? WHERE idreporte=?");
            ps.setString(1, "" + total);
            ps.setString(2, "1");
            int res = ps.executeUpdate();

            if (res > 0) {

                // limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Modificar usuario");
                //   limpiar();
            }

            conn.close();

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    public void aut2() {
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        try {

            Connection con = conn.getConexion();
            ps = con.prepareStatement("SELECT * FROM aut WHERE id = ?");
            ps.setString(1, "1");

            rs = ps.executeQuery();

            if (rs.next()) {

                txtnombre.setText(rs.getString("aut1"));

            } else {
                JOptionPane.showMessageDialog(null, "El usuario no se encuentra en el registro");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    private void limpiar() {
        txtvalor.setText("");
        comunes.setSelectedIndex(0);
    }

    private boolean validaIngresos(java.awt.event.KeyEvent evt, int num) {

        char validar = evt.getKeyChar();
        if (num == 1) {
            if (Character.isDigit(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        } else {
            if (Character.isLetter(validar)) {
                getToolkit().beep();
                evt.consume();
                return true;
            }
        }

        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comunes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtcuotas;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel txtcedula2;
    public static javax.swing.JLabel txtnombre;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
