/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;


import Paneles.Ingresos;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import paneles.CambiaPanel;
import proyingresos.Conexion;
import proyingresos.PnlEgresos;
import proyingresos.Reportepanel;
import proyingresos.pnlMultas;
import proyingresos.registropanel;

/**
 *
 * @author Kevin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
     txtnombre.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        Usuarios = new rsbuttom.RSButtonMetro();
        Ingresos = new rsbuttom.RSButtonMetro();
        Egresos = new rsbuttom.RSButtonMetro();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlImagen = new javax.swing.JPanel();
        Reporte = new rsbuttom.RSButtonMetro();
        txtnombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(765, 631));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(603, 626));
        jPanel1.setMinimumSize(new java.awt.Dimension(603, 626));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1240, 60));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuarios.setBackground(new java.awt.Color(204, 204, 204));
        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/users1.png"))); // NOI18N
        Usuarios.setText("Socios");
        Usuarios.setColorNormal(new java.awt.Color(204, 204, 204));
        Usuarios.setColorPressed(new java.awt.Color(102, 102, 102));
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuariosMousePressed(evt);
            }
        });
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        pnlMenu.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 90));

        Ingresos.setBackground(new java.awt.Color(204, 204, 204));
        Ingresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/ingresos.png"))); // NOI18N
        Ingresos.setText("Ingresos");
        Ingresos.setColorNormal(new java.awt.Color(204, 204, 204));
        Ingresos.setColorPressed(new java.awt.Color(102, 102, 102));
        Ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresosMousePressed(evt);
            }
        });
        Ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosActionPerformed(evt);
            }
        });
        pnlMenu.add(Ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 240, 100));

        Egresos.setBackground(new java.awt.Color(204, 204, 204));
        Egresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/egresos.png"))); // NOI18N
        Egresos.setText("Egresos");
        Egresos.setColorNormal(new java.awt.Color(204, 204, 204));
        Egresos.setColorPressed(new java.awt.Color(102, 102, 102));
        Egresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EgresosMousePressed(evt);
            }
        });
        Egresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgresosActionPerformed(evt);
            }
        });
        pnlMenu.add(Egresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 100));

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 290));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(765, 900));
        pnlPrincipal.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/fondo_Img_prns.jpg"))); // NOI18N
        pnlPrincipal.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 990, 720));

        pnlImagen.setBackground(new java.awt.Color(255, 255, 255));
        pnlImagen.setLayout(new javax.swing.BoxLayout(pnlImagen, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnlImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 930, 720));

        Reporte.setBackground(new java.awt.Color(204, 204, 204));
        Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/informe2.png"))); // NOI18N
        Reporte.setText("Reporte");
        Reporte.setColorNormal(new java.awt.Color(204, 204, 204));
        Reporte.setColorPressed(new java.awt.Color(102, 102, 102));
        Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReporteMousePressed(evt);
            }
        });
        Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteActionPerformed(evt);
            }
        });
        jPanel1.add(Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 100));

        txtnombre.setText("...");
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
  
        int posicion = this.pnlMenu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -250, 2, 2,  pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-250, 0, 2, 2, pnlMenu);

        }  
    }//GEN-LAST:event_btnMenuActionPerformed

    private void IngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosActionPerformed

        if(this.Ingresos.isSelected()){

            this.Usuarios.setColorNormal(new Color(204,204,204));
            this.Usuarios.setColorHover(new Color(38,86,186));
            this.Usuarios.setColorPressed(new Color(204,204,204));

            this.Egresos.setColorNormal(new Color(204,204,204));
            this.Egresos.setColorHover(new Color(38,86,186));
            this.Egresos.setColorPressed(new Color(204,204,204));

            this.Ingresos.setColorNormal(new Color(102,102,102));
            this.Ingresos.setColorHover(new Color(102,102,102));
            this.Ingresos.setColorPressed(new Color(102,102,102));
            
            this.Reporte.setColorNormal(new Color(204,204,204));
            this.Reporte.setColorHover(new Color(38,86,186));
            this.Reporte.setColorPressed(new Color(204,204,204));

            new CambiaPanel(pnlPrincipal, new Ingresos());
        }else{
            this.Ingresos.setColorNormal(new Color(102,102,102));
            this.Ingresos.setColorHover(new Color(38,86,186));
            this.Ingresos.setColorPressed(new Color(102,102,102));

        }

    }//GEN-LAST:event_IngresosActionPerformed

    private void IngresosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresosMousePressed
        this.Usuarios.setSelected(false);
        this.Egresos.setSelected(false);
        this.Ingresos.setSelected(true);
        this.Reporte.setSelected(false);

    }//GEN-LAST:event_IngresosMousePressed

    private void EgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgresosActionPerformed
        String s=txtnombre.getText();
        System.out.println(s);
        capturar();
        if(this.Egresos.isSelected()){
            this.Usuarios.setColorNormal(new Color(204,204,204));
            this.Usuarios.setColorHover(new Color(38,86,186));
            this.Usuarios.setColorPressed(new Color(204,204,204));

            this.Egresos.setColorNormal(new Color(102,102,102));
            this.Egresos.setColorHover(new Color(102,102,102));
            this.Egresos.setColorPressed(new Color(102,102,102));

            this.Ingresos.setColorNormal(new Color(204,204,204));
            this.Ingresos.setColorHover(new Color(38,86,186));
            this.Ingresos.setColorPressed(new Color(204,204,204));
            
            this.Reporte.setColorNormal(new Color(204,204,204));
            this.Reporte.setColorHover(new Color(38,86,186));
            this.Reporte.setColorPressed(new Color(204,204,204));

            new CambiaPanel(pnlPrincipal, new PnlEgresos());

        }else{
            this.Egresos.setColorNormal(new Color(102,102,102));
            this.Egresos.setColorHover(new Color(38,86,186));
            this.Egresos.setColorPressed(new Color(102,102,102));

        }

    }//GEN-LAST:event_EgresosActionPerformed

    private void EgresosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EgresosMousePressed

        this.Usuarios.setSelected(false);
        this.Egresos.setSelected(true);
        this.Ingresos.setSelected(false);
        this.Reporte.setSelected(false);
    }//GEN-LAST:event_EgresosMousePressed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed

        if(this.Usuarios.isSelected()){

            this.Usuarios.setColorNormal(new Color(102,102,102));
            this.Usuarios.setColorHover(new Color(102,102,102));
            this.Usuarios.setColorPressed(new Color(102,102,102));

            this.Egresos.setColorNormal(new Color(204,204,204));
            this.Egresos.setColorHover(new Color(38,86,186));
            this.Egresos.setColorPressed(new Color(204,204,204));

            this.Ingresos.setColorNormal(new Color(204,204,204));
            this.Ingresos.setColorHover(new Color(38,86,186));
            this.Ingresos.setColorPressed(new Color(204,204,204));
            
            this.Reporte.setColorNormal(new Color(204,204,204));
            this.Reporte.setColorHover(new Color(38,86,186));
            this.Reporte.setColorPressed(new Color(204,204,204));


            new CambiaPanel(pnlPrincipal, new registropanel());

        }else{
            this.Usuarios.setColorNormal(new Color(102,102,102));
            this.Usuarios.setColorHover(new Color(38,86,186));
            this.Usuarios.setColorPressed(new Color(102,102,102));

        }

    }//GEN-LAST:event_UsuariosActionPerformed

    private void UsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMousePressed

        this.Usuarios.setSelected(true);
        this.Egresos.setSelected(false);
        this.Ingresos.setSelected(false);
        this.Reporte.setSelected(false);
    }//GEN-LAST:event_UsuariosMousePressed

    private void ReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteMousePressed
        this.Usuarios.setSelected(false);
        this.Egresos.setSelected(false);
        this.Ingresos.setSelected(false);
        this.Reporte.setSelected(true);
    }//GEN-LAST:event_ReporteMousePressed

    private void ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteActionPerformed
        if(this.Reporte.isSelected()){
            this.Usuarios.setColorNormal(new Color(204,204,204));
            this.Usuarios.setColorHover(new Color(38,86,186));
            this.Usuarios.setColorPressed(new Color(204,204,204));

            this.Egresos.setColorNormal(new Color(102,102,102));
            this.Egresos.setColorHover(new Color(102,102,102));
            this.Egresos.setColorPressed(new Color(102,102,102));

            this.Ingresos.setColorNormal(new Color(204,204,204));
            this.Ingresos.setColorHover(new Color(38,86,186));
            this.Ingresos.setColorPressed(new Color(204,204,204));
            
            this.Reporte.setColorNormal(new Color(204,204,204));
            this.Reporte.setColorHover(new Color(38,86,186));
            this.Reporte.setColorPressed(new Color(204,204,204));

            new CambiaPanel(pnlPrincipal, new Reportepanel());

        }else{
            this.Reporte.setColorNormal(new Color(102,102,102));
            this.Reporte.setColorHover(new Color(38,86,186));
            this.Reporte.setColorPressed(new Color(102,102,102));

        }
    }//GEN-LAST:event_ReporteActionPerformed

    public void capturar(){
    PreparedStatement ps = null;
        
        try {
            Conexion objCon = new Conexion();
            com.mysql.jdbc.Connection conn = objCon.getConexion();

            ps = conn.prepareStatement("UPDATE aut SET aut1=? WHERE id=?");
            ps.setString(1, txtnombre.getText());
            ps.setString(2, "1");
            
            ps.execute();
//JOptionPane.showMessageDialog(null, "Usuario Modificado");
            
                
            
                
                 //limpiar();
                           
                 
            

         //   conn.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Modificar usuario");
            System.err.println(ex);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal open = new Principal();
                open.setVisible(true);
                open.setResizable(false);
                
                Ingresos ing = new Ingresos();
                ing.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Egresos;
    private rsbuttom.RSButtonMetro Ingresos;
    private rsbuttom.RSButtonMetro Reporte;
    private rsbuttom.RSButtonMetro Usuarios;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlImagen;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JLabel txtnombre;
    // End of variables declaration//GEN-END:variables
}
